ADTArray_NC := ADTArray_NonContiguous
ADTArray := ADTArray
ADTStack := ADTStack
FLAGS := -Wall -g

all: ADTArray 

ADTStack:
	gcc $(ADTStack).c $(FLAGS) -o $(ADTStack)
ADTArray:
	gcc $(ADTArray).c $(FLAGS) -o $(ADTArray)
clean:
	# CLEANING
	rm $(ADTArray)
# rm $(ADTStack)