ADTArray := ADTArray
ADTStack := ADTStack
FLAGS := -Wall -g

all: ADTArray ADTStack

ADTStack:
	gcc $(ADTStack).c $(FLAGS) -o $(ADTStack)
ADTArray:
	gcc $(ADTArray).c $(FLAGS) -o $(ADTArray)
clean:
	rm $(ADTArray)
	rm $(ADTStack)